{% set version = "218.0.0" %}

package:
  name: google-cloud-sdk
  version: {{ version }}

source:
  fn: google-cloud-sdk-{{ version }}-linux-x86_64.tar.gz  # [linux]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-linux-x86_64.tar.gz  # [linux]
  sha256: d6b59e12dec1bff384118e154e5bdceea40f8820a515bd54c26e6a5acfafeb7b  # [linux]
  fn: google-cloud-sdk-{{ version }}-darwin-x86_64.tar.gz  # [osx]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-darwin-x86_64.tar.gz  # [osx]
  sha256: 4892e8919ec075cd9e52fb55acb7d98ee3866bb146291813fb92eda13fd2d75f  # [osx]

build:
  number: 1000
  skip: True  # [win]

requirements:
  build:
    - python
  run:
    - python

test:
  commands:
    - gcloud version
    - gsutil help  # [py2k]

about:
  home: https://cloud.google.com/sdk/
  license: Apache v2.0
  license_family: Apache
  summary: Command-line interface for Google Cloud Platform products and services

extra:
  recipe-maintainers:
    - chapmanb
    - scopatz
