{% set version = "208.0.1" %}

package:
  name: google-cloud-sdk
  version: {{ version }}

source:
  fn: google-cloud-sdk-{{ version }}-linux-x86_64.tar.gz  # [linux]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-linux-x86_64.tar.gz  # [linux]
  sha256: 4efea48ff1c8bb81a68cb651380a7e1de90142f9026c9ed52bd55561e3d094eb  # [linux]
  fn: google-cloud-sdk-{{ version }}-darwin-x86_64.tar.gz  # [osx]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-darwin-x86_64.tar.gz  # [osx]
  sha256: 32cd71920fad3ceb36cd938d4b23f672e644f7cfe7e65992fae7ef00745f569b  # [osx]

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - python
  run:
    - python

test:
  commands:
    - gcloud version
    - gsutil help  # [py2k]

about:
  home: https://cloud.google.com/sdk/
  license: Apache v2.0
  license_family: Apache
  summary: Command-line interface for Google Cloud Platform products and services

extra:
  recipe-maintainers:
    - chapmanb
    - scopatz
