{% set version = "211.0.0" %}

package:
  name: google-cloud-sdk
  version: {{ version }}

source:
  fn: google-cloud-sdk-{{ version }}-linux-x86_64.tar.gz  # [linux]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-linux-x86_64.tar.gz  # [linux]
  sha256: 53becbf0a512bc1f928921a116c9a397cbf172621849e1d85dd2f906933b2241  # [linux]
  fn: google-cloud-sdk-{{ version }}-darwin-x86_64.tar.gz  # [osx]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-darwin-x86_64.tar.gz  # [osx]
  sha256: 33af4e653b7619cef2f30e89b24f662a4c8a9bc57c16a41377aa522c91e886af  # [osx]

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - python
  run:
    - python

test:
  commands:
    - gcloud version
    - gsutil help  # [py2k]

about:
  home: https://cloud.google.com/sdk/
  license: Apache v2.0
  license_family: Apache
  summary: Command-line interface for Google Cloud Platform products and services

extra:
  recipe-maintainers:
    - chapmanb
    - scopatz
