{% set version = "268.0.0" %}

package:
  name: google-cloud-sdk
  version: {{ version }}

source:
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-linux-x86_64.tar.gz  # [linux]
  sha256: bc8fa3a096421659d557b408d46dbbd565420d2f2cab99198ca0e8791f4d59a0  # [linux]
  url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ version }}-darwin-x86_64.tar.gz  # [osx]
  sha256: 759a9ecf9406b2a8758e8e1cedd6d461ad6f0834e80f785c91425e8b209c0082  # [osx]

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - python
  run:
    - python

test:
  commands:
    - gcloud version
    - gsutil help  # [py2k]

about:
  home: https://cloud.google.com/sdk/
  license: Apache v2.0
  license_family: Apache
  license_file: LICENSE
  summary: Command-line interface for Google Cloud Platform products and services

extra:
  recipe-maintainers:
    - chapmanb
    - scopatz
