travis:
  secure:
    BINSTAR_TOKEN: LhGHaJkk6MjIiQN2hj/UdQ0+y694YESMpRgo9P0ZLcIv9QqDPoAKcJqldEnB8ij3lVCLHa6H7Rjr1hlUunCiKUPNcLOtb2Flr2hZZfm96ahoR3weOpN4COvIEWr2euoqUFJN4W6x6Wg2czPqKNan1HURYz0BrBh+Yc3BxX1wl4o5dmI/Em/NOVPFNYB6dmrOTL1GyhUtiZZHeY2ubgpRnz9yDAEFcdvH5rAgzyaoAkqZuHvP+m22JPBrw9RfUqCDMQBMbd6011LoS+eh56cark/4cgG+bMUFqHACA8bbbtxfk8JNhKOjcHsLo4X4WtELw3cXO14Z9ORoInxb46C8UedPKbJZdwpAYZf4JyMssqi1E3SMxZlDzQVRFqtVExSpAY9vlMlKQ8IrcE2T5yz7kzexhKeqJR6Z43t+VJks8UYuPHTGz6Z35DUyFWdI/2hiEIi56a1JjMqNP/dj5N2TXZXG4iw35De+Nv5pwGtyZ3Vh/0EyqeoKRMOoYmuBGAWKy0Z35dn5OtpuPpd+F0s19UHxNwekSyDyvT+2UgkhGeaMdR1iUnrAd569eRZ25XqKFWApLtDl08Te8A3DMZZo0M9d/gOEwP/0POsXCqKASGuS5d/ZUFT6i2XbA5WPU9lkC9Su0j8XwH6LC0e8EvZ6K9PFSbc1FMNdPr0y4tgDKEM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
